### ISSUE TITLE
Add test coverage badge using https://coveralls.io

### ISSUE THREAD

**Issue by kevgo** [mjhm/lodash-match-pattern#14]
Example: https://github.com/Originate/asca

**Comment by mjhm** [comment]
Thanks for the suggestion.  I looked into this using istanbul. It wasn't as plug-n-play as I would have hoped because I've got this `_parser.js` file that's auto-generated via a "prepublish" script.  It only showed 80% coverage, while everything else showed >95% coverage. I could probably make this work somehow, but it's crossed the cost/benefit line for me.

**Comment by kevgo** [comment]
Okay, not feeling strongly about code coverage as a metric anyways  :)
